version: '2'

services:
  cyoa-frontend:
    container_name: cyoa-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./certs:/config/keys/letsencrypt"
