version: '2'

services:
  rigamo:
    container_name: rigamo-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./certs:/config/keys/letsencrypt"
